# Generated by Django 5.2.4 on 2025-07-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0002_employee_delete_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
